### ISSUE TITLE
Missing documentation at readthedocs.org

### ISSUE THREAD

**Issue by fridex** [fauststream/mode#2]
Linked [web docs](http://mode.readthedocs.org/) in the README file refer to documentation that does not exist (I get 404). Not set up yet?

**Comment by ask** [comment]
Yeah! It seems someone changed the password for the Readthedocs asksol account.  That's the account that manages the Celery project documentation, and it's connected to my `ask` github account.

I tried creating a new account, but it won't let me link it with github, ujst telling me "Github user ask is already connected using a different account" or similar.

So I got stuck there :)

**Comment by ask** [comment]
Fixed by creating a new Github user to manage docs: http://mode.readthedocs.io/en/latest/ :tada:
